export const departments = [
  "HR",
  "IT",
  "Finance",
  "Marketing",
  "Sales",
  "Operations",
];

export const roles = [
  "Manager",
  "Developer",
  "Analyst",
  "Designer",
  "Associate",
  "Director",
];

export const mockEmployees = [
  {
    id: 1,
    firstName: "Rahul",
    lastName: "Verma",
    email: "rahul.verma@company.com",
    department: "HR",
    role: "Manager",
  },
  {
    id: 2,
    firstName: "Sneha",
    lastName: "Sharma",
    email: "sneha.sharma@company.com",
    department: "IT",
    role: "Developer",
  },
  {
    id: 3,
    firstName: "Aman",
    lastName: "Gupta",
    email: "aman.gupta@company.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 4,
    firstName: "Priya",
    lastName: "Nair",
    email: "priya.nair@company.com",
    department: "Marketing",
    role: "Designer",
  },
  {
    id: 5,
    firstName: "Karan",
    lastName: "Yadav",
    email: "karan.yadav@company.com",
    department: "Sales",
    role: "Associate",
  },
  {
    id: 6,
    firstName: "Ritika",
    lastName: "Singh",
    email: "ritika.singh@company.com",
    department: "Operations",
    role: "Director",
  },
  {
    id: 7,
    firstName: "Manish",
    lastName: "Patel",
    email: "manish.patel@company.com",
    department: "IT",
    role: "Manager",
  },
  {
    id: 8,
    firstName: "Anjali",
    lastName: "Mehra",
    email: "anjali.mehra@company.com",
    department: "HR",
    role: "Associate",
  },
  {
    id: 9,
    firstName: "Rohit",
    lastName: "Bose",
    email: "rohit.bose@company.com",
    department: "Finance",
    role: "Manager",
  },
  {
    id: 10,
    firstName: "Neha",
    lastName: "Desai",
    email: "neha.desai@company.com",
    department: "Marketing",
    role: "Developer",
  },
  {
    id: 11,
    firstName: "Aarav",
    lastName: "Kapoor",
    email: "aarav.kapoor@company.com",
    department: "IT",
    role: "Developer",
  },
  {
    id: 12,
    firstName: "Meera",
    lastName: "Iyer",
    email: "meera.iyer@company.com",
    department: "HR",
    role: "Executive",
  },
  {
    id: 13,
    firstName: "Nikhil",
    lastName: "Choudhary",
    email: "nikhil.choudhary@company.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 14,
    firstName: "Tanvi",
    lastName: "Joshi",
    email: "tanvi.joshi@company.com",
    department: "Marketing",
    role: "Coordinator",
  },
  {
    id: 15,
    firstName: "Yash",
    lastName: "Rana",
    email: "yash.rana@company.com",
    department: "Sales",
    role: "Associate",
  },
];
